// ==========================================
// pattern-loader.js
// Loads compiled patterns from patterns.compiled.yaml
// and provides a runtime interpreter for the DSL match syntax.
//
// * --- RESPONSIBILITIES ---
//   1. Load patterns.compiled.yaml at startup (once, cached)
//   2. Detect file language from extension
//   3. Scan imports to detect active frameworks
//   4. Filter patterns by lang + framework (Optimization)
//   5. Interpret DSL match blocks against tree-sitter nodes
//   6. Return matched pattern labels
//
// * --- DSL KEYWORDS SUPPORTED ---
//   ANY  <collection> IN <node.prop> WHERE (<condition>)
//   ALL  <collection> IN <node.prop> WHERE (<condition>)
//   NONE <collection> IN <node.prop> WHERE (<condition>)
//   AND, OR, NOT
//   ==, !=
//   starts_with, starts_with_capital
//
// * --- USAGE ---
//   const { matchPattern } = require('./pattern-loader');
//   const label = matchPattern(node, filePath, importedFrameworks);
//   if (label) output += label;
// ==========================================

"use strict";

const fs = require("fs");
const path = require("path");
const yaml = require("js-yaml");

// ==========================================
// CONSTANTS & MAPS
// ==========================================

// ! Path to the compiled pattern file generated by compile-patterns.js
// ! Do not edit the compiled file directly; edit the source YAMLs.
const COMPILED_FILE = path.join(__dirname, "patterns.compiled.yaml");

// ? Maps file extensions to language identifiers used in our pattern files
const EXT_TO_LANG = {
  ".js": "js",
  ".jsx": "js",
  ".ts": "ts",
  ".tsx": "ts",
};

// ? Maps import sources to framework identifiers
// e.g., import { useState } from 'react' → flags framework as 'react'
const IMPORT_TO_FRAMEWORK = {
  react: "react",
  "react-dom": "react",
  vue: "vue",
  "@vue/composition-api": "vue",
  express: "express",
  "@nestjs/common": "nestjs",
  "@nestjs/core": "nestjs",
  "@nestjs/microservices": "nestjs",
  fastify: "fastify",
  koa: "koa",
};

// ==========================================
// PATTERN CACHE
// ==========================================

// * Patterns are loaded once at startup and cached in memory.
let _cachedPatterns = null;

function loadPatterns() {
  if (_cachedPatterns) return _cachedPatterns;

  if (!fs.existsSync(COMPILED_FILE)) {
    console.log("[pattern-loader] [WARN] patterns.compiled.yaml not found.");
    _cachedPatterns = [];
    return _cachedPatterns;
  }

  try {
    const content = fs.readFileSync(COMPILED_FILE, "utf8");
    const parsed = yaml.load(content);

    if (!parsed || !Array.isArray(parsed.patterns)) {
      console.log("[pattern-loader] [WARN] patterns.compiled.yaml has no patterns array.");
      _cachedPatterns = [];
      return _cachedPatterns;
    }

    _cachedPatterns = parsed.patterns;
    console.log(`[pattern-loader] [OK] Loaded ${_cachedPatterns.length} patterns.`);
    return _cachedPatterns;
  } catch (err) {
    console.log(`[pattern-loader] [ERROR] Failed to load patterns: ${err.message}`);
    _cachedPatterns = [];
    return _cachedPatterns;
  }
}

// ==========================================
// DETECTION ENGINES
// ==========================================

function detectLanguage(filePath) {
  const ext = path.extname(filePath).toLowerCase();
  return EXT_TO_LANG[ext] || null;
}

function detectFrameworks(rootNode) {
  const frameworks = new Set();

  for (const child of rootNode.children) {
    let importSource = null;

    if (child.type === "import_statement") {
      const stringNode = child.children.find((c) => c.type === "string");
      if (stringNode) {
        importSource = stringNode.text.replace(/['"]/g, "");
      }
    }

    if (
      child.type === "lexical_declaration" ||
      child.type === "variable_declaration"
    ) {
      for (const declarator of child.children) {
        if (declarator.type === "variable_declarator") {
          const value = declarator.childForFieldName("value");
          if (value && value.type === "call_expression") {
            const fn = value.childForFieldName("function");
            if (fn && fn.text === "require") {
              const args = value.childForFieldName("arguments");
              const str = args && args.children.find((c) => c.type === "string");
              if (str) importSource = str.text.replace(/['"]/g, "");
            }
          }
        }
      }
    }

    if (importSource) {
      if (IMPORT_TO_FRAMEWORK[importSource]) {
        frameworks.add(IMPORT_TO_FRAMEWORK[importSource]);
      }
      for (const [key, framework] of Object.entries(IMPORT_TO_FRAMEWORK)) {
        if (importSource.startsWith(key)) {
          frameworks.add(framework);
        }
      }
    }
  }

  return frameworks;
}

// ==========================================
// DSL INTERPRETER
// ==========================================

/**
 * FIX: Smart Deep-Unwrapper
 * Recursively unwraps statement containers to find the core logic inside.
 */
function unwrapCallExpression(node) {
  if (!node) return null;
  
  if (node.type === "call_expression") return node;
  
  if (node.type === "await_expression") {
    return node.children.find((c) => c.type === "call_expression") || null;
  }

  const wrapper = node.children.find((c) => 
    ["call_expression", "await_expression", "assignment_expression", "return_statement", "variable_declarator"].includes(c.type)
  );

  if (!wrapper) return null;

  if (wrapper.type === "assignment_expression" || wrapper.type === "return_statement" || wrapper.type === "variable_declarator") {
    const inner = wrapper.children.find((c) => c.type === "call_expression" || c.type === "await_expression");
    return unwrapCallExpression(inner);
  }

  return unwrapCallExpression(wrapper);
}

/**
 * Resolves a DSL property path on a tree-sitter node.
 */
function resolveProperty(node, propPath) {
  // ! FIX: Strip ANY variable prefix before the dot dynamically. 
  // ! (e.g., 'declarator.call', 'child.method_call', 'node.name' -> all become just 'call' / 'method_call' / 'name')
  const prop = propPath.includes('.') ? propPath.split('.').pop() : propPath;

  switch (prop) {
    case "children":
      return node.children || [];

    case "name": {
      const nameNode = node.childForFieldName?.("name");
      return nameNode ? nameNode.text : null;
    }

    case "call": {
      const callExpr = unwrapCallExpression(node);
      return callExpr ? callExpr.childForFieldName?.("function")?.text || null : null;
    }

    case "method_call": {
      const callExpr = unwrapCallExpression(node);
      if (!callExpr) return null;

      const fn = callExpr.childForFieldName?.("function");
      if (!fn || fn.type !== "member_expression") return null;

      const obj = fn.childForFieldName?.("object")?.text;
      const method = fn.childForFieldName?.("property")?.text;
      return obj && method ? `${obj}.${method}` : null;
    }

    case "decorators": {
      return node.children.filter((c) => c.type === "decorator");
    }

    case "decorator_name": {
      if (node.type !== "decorator") return null;
      
      const callExpr = node.children.find((c) => c.type === "call_expression");
      if (callExpr) {
        return callExpr.childForFieldName?.("function")?.text || null;
      }
      const ident = node.children.find((c) => c.type === "identifier");
      return ident ? ident.text : null;
    }

    case "params":
    case "parameters": {
      const params = node.childForFieldName?.("parameters");
      return params ? params.text : null;
    }

    default:
      return null;
  }
}

function evaluateCondition(node, condition, itemNode) {
  const trimmed = condition.trim();

  if (trimmed.includes("starts_with_capital")) {
    const targetNode = itemNode || node;
    const name = resolveProperty(targetNode, trimmed.split("starts_with_capital")[0].trim());
    return typeof name === "string" && /^[A-Z]/.test(name);
  }

  if (trimmed.includes("starts_with")) {
    const parts = trimmed.split("starts_with");
    const prop = parts[0].trim();
    const prefix = parts[1].trim();
    const targetNode = itemNode || node;
    const value = resolveProperty(targetNode, prop);
    return typeof value === "string" && value.startsWith(prefix);
  }

  if (trimmed.includes("!=")) {
    const [left, right] = trimmed.split("!=").map((s) => s.trim());
    const targetNode = itemNode || node;
    const value = resolveProperty(targetNode, left);
    return value !== right;
  }

  if (trimmed.includes("==")) {
    const [left, right] = trimmed.split("==").map((s) => s.trim());
    const targetNode = itemNode || node;
    const value = resolveProperty(targetNode, left);
    return value === right;
  }

  return false;
}

function evaluateMatch(node, matchStr) {
  if (!matchStr || !matchStr.trim()) return true;

  const andParts = splitTopLevel(matchStr.trim(), "AND");
  if (andParts.length > 1) {
    return andParts.every((part) => evaluateMatch(node, part.trim()));
  }

  const orParts = splitTopLevel(matchStr.trim(), "OR");
  if (orParts.length > 1) {
    return orParts.some((part) => evaluateMatch(node, part.trim()));
  }

  const str = matchStr.trim();

  const quantifierMatch = str.match(
    /^(ANY|ALL|NONE)\s+(\w+)\s+IN\s+([\w.]+)\s+WHERE\s+\(([^)]+)\)/i,
  );

  if (quantifierMatch) {
    const quantifier = quantifierMatch[1].toUpperCase();
    const collection = quantifierMatch[3]; 
    const condition = quantifierMatch[4];  

    const items = resolveProperty(node, collection);
    
    if (!Array.isArray(items) || items.length === 0) {
      return quantifier === "NONE";
    }

    const orConditions = condition.split(/\s+OR\s+/).map((c) => c.trim());
    const testItem = (item) =>
      orConditions.some((cond) => evaluateCondition(node, cond, item));

    switch (quantifier) {
      case "ANY":  return items.some(testItem);
      case "ALL":  return items.every(testItem);
      case "NONE": return items.every((item) => !testItem(item));
      default:     return false;
    }
  }

  return evaluateCondition(node, str, null);
}

function splitTopLevel(str, keyword) {
  const parts = [];
  let depth = 0;
  let current = "";
  const kw = ` ${keyword} `;
  let i = 0;

  while (i < str.length) {
    if (str[i] === "(") depth++;
    if (str[i] === ")") depth--;

    if (depth === 0 && str.startsWith(kw, i)) {
      parts.push(current);
      current = "";
      i += kw.length;
      continue;
    }

    current += str[i];
    i++;
  }

  parts.push(current);
  return parts.length > 1 ? parts : [str];
}

// ==========================================
// LABEL BUILDER
// ==========================================

function buildLabel(label, node) {
  return label
    .replace(/{name}/g, () => {
      const nameNode = node.childForFieldName?.("name");
      return nameNode ? nameNode.text : "unknown";
    })
    .replace(/{params}/g, () => {
      const params = node.childForFieldName?.("parameters");
      return params ? params.text : "()";
    })
    .replace(/{returnType}/g, () => {
      const rt = node.children.find((c) => c.type === "type_annotation");
      return rt ? rt.text : "";
    })
    .replace(/{declaration}/g, () => {
      return node.text.replace(/\s+/g, " ").replace(/;$/, "").trim();
    })
    .replace(/{call}/g, () => {
      const expr = node.children.find(
        (c) => c.type === "call_expression" || c.type === "expression_statement",
      );
      if (expr) {
        const fn = expr.childForFieldName?.("function");
        return fn ? fn.text : "unknown";
      }
      return "unknown";
    })
    .replace(/{deps}/g, () => {
      const depsMatch = node.text.match(/,\s*\[([^\]]*)\]\s*\)\s*;?\s*$/);
      return depsMatch ? depsMatch[1].trim() : "";
    })
    .replace(/{object}/g, () => {
      const callExpr = node.children.find((c) => c.type === "call_expression");
      if (!callExpr) return "unknown";
      const fn = callExpr.childForFieldName?.("function");
      if (!fn || fn.type !== "member_expression") return "unknown";
      return fn.childForFieldName?.("object")?.text || "unknown";
    })
    .replace(/{method}/g, () => {
      const callExpr = node.children.find((c) => c.type === "call_expression");
      if (!callExpr) return "unknown";
      const fn = callExpr.childForFieldName?.("function");
      if (!fn || fn.type !== "member_expression") return "unknown";
      return fn.childForFieldName?.("property")?.text || "unknown";
    })
    .replace(/{path}/g, () => {
      const callExpr = node.children.find((c) => c.type === "call_expression");
      if (!callExpr) return "";
      const args = callExpr.childForFieldName?.("arguments");
      if (!args) return "";
      const str = args.children.find((c) => c.type === "string");
      return str ? str.text : "";
    })
    .replace(/{members}/g, () => {
      const body = node.childForFieldName?.("body");
      if (!body) return "";
      const names = [];
      for (const child of body.children) {
        const nameNode = child.childForFieldName?.("name");
        if (nameNode) names.push(nameNode.text);
      }
      return names.length > 0 ? `{ ${names.join(", ")} }` : "";
    })
    .replace(/{exports}/g, () => {
      return node.text.replace(/\s+/g, " ").replace(/;$/, "").trim();
    });
}

// ==========================================
// PUBLIC API
// ==========================================

function matchPattern(node, lang, frameworks) {
  const patterns = loadPatterns();

  for (const pattern of patterns) {
    if (pattern.lang !== lang) continue;
    if (pattern.framework && !frameworks.has(pattern.framework)) continue;
    
    // ! FIX: Deep Target Property Matching
    // Ensures that patterns requiring specific objects/properties (like 'module.exports') 
    // do not falsely intercept standard expression statements like hooks or routes.
    if (pattern.target) {
      if (pattern.target.kind && node.type !== pattern.target.kind) continue;
      
      if (pattern.target.object || pattern.target.property) {
        let isMatch = false;
        if (node.type === "expression_statement") {
          const assign = node.children.find((c) => c.type === "assignment_expression");
          if (assign) {
            const left = assign.childForFieldName("left");
            if (left && left.type === "member_expression") {
              const obj = left.childForFieldName("object")?.text;
              const prop = left.childForFieldName("property")?.text;
              
              const matchObj = !pattern.target.object || obj === pattern.target.object;
              const matchProp = !pattern.target.property || prop === pattern.target.property;
              
              if (matchObj && matchProp) isMatch = true;
            }
          }
        }
        if (!isMatch) continue;
      }
    }

    if (pattern.match) {
      const matched = evaluateMatch(node, pattern.match);
      if (!matched) continue;
    }

    return buildLabel(pattern.label, node);
  }

  return null;
}

// ==========================================
// EXPORTS
// ==========================================

module.exports = {
  matchPattern,
  detectLanguage,
  detectFrameworks,
  loadPatterns,
};